spring:
  application:
    name: SheikahRegister

  datasource:
    url: jdbc:postgresql://localhost:5432/sheikahregister
    username: postgres
    password: ADMIN

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
